Chore/add pandas support for get generator operations list
craft-ai/craft-ai-client-python pull request #224
Opened 2021-03-24 11:22 UTC by matthieu-boussard

2021-03-29 07:51 UTC, matthieu-boussard commented on CHANGELOG.md
> +## [2.1.2](https://github.com/craft-ai/craft-ai-client-python/compare/v2.1.0...v2.1.1) - 2021-03-26 ##
```suggestion
```
You just have to set your changelog entry under the unreleased entry (will be moved to the proper version when released)

2021-03-29 07:54 UTC, matthieu-boussard commented on CHANGELOG.md
> +- Add Documentation for pandas get_generator_operations
```suggestion
- Add tests to verify the behaviour of pandas client get_generator_operations
- Add Documentation for pandas get_generator_operations
```
You can remove those two lines since they are included in the first one ( for every feature you must have tests and doc)

2021-03-29 07:55 UTC, matthieu-boussard commented on README.md
> +# 2019-12-31 23:00:00+00:00   my_agent_1  1577829600                   2                 23           +02:00                      ON
what is the index of your dataframe ? in generators, you may have two identical timestamps

2021-03-29 07:55 UTC, matthieu-boussard commented on craft_ai/pandas/client.py
> +        df.index = pd.to_datetime(
you may have two identical timestamp for a a generator

2021-03-29 08:00 UTC, matthieu-boussard commented on tests/data/pandas_valid_data.py
> +SIMPLE_AGENT_DATA = pd.DataFrame(
you already have a dataframe called SIMPLE_AGENT_DATA , it may be more interesting to reuse existing tests data (generator is a agent with a 'filter' field)

2021-04-01 14:33 UTC, matthieu-boussard commented on pyproject.toml
> +test = "poetry run pytest --durations=10 tests/test_pandas_get_generator_operations.py"
```suggestion
test = "poetry run pytest --durations=10 tests/*.py"
```

2021-04-01 14:36 UTC, matthieu-boussard commented on tests/test_pandas_get_generator_operations.py
> +        generator_configuration["filter"] = [self.agent_1_id]
your generator already have a filter flied, do you really want to override it ?

2021-04-01 15:33 UTC, Giska requested changes

2021-04-01 15:33 UTC, Giska commented on README.md
> +```
Doc should be updated from content

2021-04-02 14:38 UTC, Giska approved these changes

2021-04-02 16:06 UTC, merged